### ISSUE TITLE
Create CONTRIBUTORS.md

### ISSUE THREAD

**Issue by jorenham** [jorenham/fingerblox#3]
With names, links to github pages and roles

**Comment by luHub** [comment]
Ok!

**Comment by luHub** [comment]
Working on it, as soon it is ready will make a push request.

**Comment by luHub** [comment]
Pull Request done!
https://github.com/jorenham/fingerblox/pull/65

**Comment by luHub** [comment]
Changed Roles to Android Developer
#65
