### ISSUE TITLE
Display intermediate steps

### ISSUE THREAD

**Issue by jorenham** [jorenham/fingerblox#30]
- Skin detection
- Histogram equalisation
- Skeletization
- Thinning
- Minutiae

**Comment by shashankpr** [comment]
Only the original image, the skeleton image could be displayed before the final zebra image. 
These images sometimes crash the app. Need to check on a phone.

**Comment by shashankpr** [comment]
Other intermediate steps have either nothing to show or crash the app always

**Comment by jorenham** [comment]
What about the skin detection cropping and histogram equalisation?

**Comment by jorenham** [comment]
Also, could you push what you have right now (including the crashing images), we might be able to help

**Comment by shashankpr** [comment]
![screen shot 2017-04-03 at 1 39 31 pm](https://cloud.githubusercontent.com/assets/22279111/24607650/1a4a096e-1873-11e7-827f-86b8af00c34a.png)

**Comment by Roccy** [comment]
That has to do with having a too small image passed on to the opencv. Have
you rebased on master already?


Op ma 3 apr. 2017 om 13:40 schreef Shashank Rao <notifications@github.com>:

**Comment by shashankpr** [comment]
Yes ! I had rebased it on master !

**Comment by Roccy** [comment]
It's your phone, mine doesn't crash with it.

**Comment by Roccy** [comment]
It could be maybe possible to show the intermediate steps in the preview (the ellipse). Now it shows the zebra without keypoints, and the zebra with keypoints later, even if you go back to the preview.

**Comment by jorenham** [comment]
Reassigned due to broken phone of @Roccy
