### ISSUE TITLE
Get started on the report

### ISSUE THREAD

**Issue by jorenham** [jorenham/fingerblox#38]
In google docs for now so we can all work together as one happy family.
Move over to Overleaf and IEEE stuff.

**Comment by Saminobi** [comment]
Both platforms (as the repo is public, these links are only for viewing, links for writing can be found in Slack conversations):

1. [Overleaf (With IEEE layout)](https://www.overleaf.com/read/rgfgshdnpkhr)
2. [Google Docs](https://docs.google.com/document/d/1i00Jio3MYiEpwcIjN6dyZs8hsday0fpol-XJ1wp7EvA/edit?usp=sharing)

**Comment by luHub** [comment]
Hi Saminobi, let me know about the skeleton of the report to put some hands on

**Comment by Saminobi** [comment]
@luHub the skeleton is there, I will start adding content and changing probably the structure in the weekend.

**Comment by luHub** [comment]
Perfect Saminobi ley me know if you need any help, etc.
