### ISSUE TITLE
Camera fixed focus distance

### ISSUE THREAD

**Issue by jorenham** [jorenham/fingerblox#6]
Can be model specific. Image should be focused on a specified distance (e.g. 10cm)

**Comment by jorenham** [comment]
It is not possible to set the camera focal distance to a specific distance. What is possible however is to focus on an area (e.g. the "finger area")

**Comment by Roccy** [comment]
Focal distance has been set to focus continuously, which works well with the macro-lens. It's still needed to find the sweet spot, but it can be found easily in normal lighting.
