### ISSUE TITLE
Gabor filter

### ISSUE THREAD

**Issue by jorenham** [jorenham/fingerblox#61]

**Comment by luHub** [comment]
Found some information about Gabor Filters parameters choice. 

4.2 Parameter Choice
In the case of image enhancement by straight GFs, [27] and other authors (e.g. [42]) use
quadratic windows of size 11×11 pixels and choices for the standard deviation of the Gaussian
of σx = σy = 4.0, or very similar values. We agree with their arguments that the parameter
selection of σx and σy involves a trade-off between an ineffective filter (for small values of
σx and σy) and the risk of creating artifacts in the enhanced image (for large values of σx
and σy). Moreover, the same reasoning holds true for the size of the window. In analogy
to the situation during the RF estimation (see Figure 3), enlarging a rectangular window in
a region with curved ridge and valley flow increases the risk for.

**Comment by luHub** [comment]
https://github.com/clumsy/gabor-filter. I need to check if there is an OpenCv filter, too.
